[workspace]
members = ["openvpn-connect", "openvpn-connect-sys", "xtask"]
resolver = "2"

[workspace.package]
version = "0.1.2"
edition = "2024"
rust-version = "1.88"
license = "MPL-2.0"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
missing_panics_doc = "allow"
